### ISSUE TITLE
Change app icon

### ISSUE THREAD

**Issue by snufflesrea** [snufflesrea/MyClock#1]
Find free clock icon (without copyright or permission issue), if possible with cool color
change the icon to vector asset if possible
change the icon app with the downloaded icon

**Comment by Talisantos** [comment]
I can work on this

**Comment by snufflesrea** [comment]
Yeah sure.

**Comment by Talisantos** [comment]
#2 I have prepare a new vector icon and PR

**Comment by snufflesrea** [comment]
Thank you for your contribution
