### ISSUE TITLE
Set on click item for recycle view viewHolder

### ISSUE THREAD

**Issue by snufflesrea** [snufflesrea/MyClock#13]
Location where component need to be modified 
Alarm Fragment
Alarm Recycle View Adapter
![Webp net-resizeimage](https://user-images.githubusercontent.com/15926749/67369982-01256d00-f58b-11e9-9b70-c39da22d62a1.png)

Expected behavior :
When user clicked Recycle View item should open fragment_alarm_edit layout.
The data from view holder should shown on fragment_alarm_edit layout
When user click set button, the data in ROOM Database should be updated
![Webp net-resizeimage (1)](https://user-images.githubusercontent.com/15926749/67370021-100c1f80-f58b-11e9-957a-710b2d3cbf86.png)

**Comment by pr0t3us** [comment]
I would like to take care of this issue if possible.

**Comment by snufflesrea** [comment]
Yes. Go ahead & made pull request when it is ready

**Comment by pr0t3us** [comment]
Hi @snufflesrea, didn't find `AlarmFragment` or `AlarmRecycleViewAdapter` in the project. Can you check if all the changes are pushed?

**Comment by snufflesrea** [comment]
My bad, I forgot to push my work. Now the Alarm folder all has been pushed
