### ISSUE TITLE
Null Pointer Exception when inflating Recycler View

### ISSUE THREAD

**Issue by snufflesrea** [snufflesrea/MyClock#3]
The complete explanation has been posted at [stackoverflow](https://stackoverflow.com/questions/58282386/null-pointer-exception-on-recycler-view-with-text-clock-as-item)
Anybody who has been experienced same issue please help me.

**Comment by aman0408** [comment]
Can I look into it?

**Comment by snufflesrea** [comment]
Sure. I ve play with it 2 days, still didn't understand why it happened

**Comment by aman0408** [comment]
Okay working on it.

**Comment by aman0408** [comment]
Could we use a textview and regularly update it instead of a TextClock widget?

**Comment by aman0408** [comment]
I was able to produce this output. Is this the expected behavior?
![Screenshot_20191008-181037](https://user-images.githubusercontent.com/42177948/66396331-2a74c380-e9f7-11e9-955b-3144858d7745.jpg)

**Comment by snufflesrea** [comment]
It should be able to produce more than 1 item view as list. I found the bug when I tried to produce more than 1 item view. If the item view only ot is working fine as shown here. : https://i.ibb.co/MskHGL7/Webp-net-resizeimage.png

Text Clock basically is an extension of Text View. If we change this into Text View, basically we rewrite the whole thing without knowing what we need to change.

**Comment by snufflesrea** [comment]
The idea is later user able to add clock with different timezone using the fab button. So for now, my goal is UI able to display 2 or more digital clock in list view/recycler view. I put two input on clock_fragment with the same timezone

**Comment by aman0408** [comment]
I had used "DigitalClock" instead of "TextClock" and there was an issue with the heights of the item_clock.xml. They should be wrap content.
![Screenshot_20191008-183642](https://user-images.githubusercontent.com/42177948/66398255-1337d500-e9fb-11e9-9293-1cd220f1ca76.jpg)

**Comment by aman0408** [comment]
I got it working with TextClock. Should I make a pull request?

**Comment by snufflesrea** [comment]
Awesome. Just make pull request and post the screenshoot here

**Comment by aman0408** [comment]
Sure.
![Screenshot_20191008-185125](https://user-images.githubusercontent.com/42177948/66399195-c2c17700-e9fc-11e9-9a7a-a4371018cf34.jpg)

**Comment by snufflesrea** [comment]
Thank you for your contribution. 
I made such a silly mistake :))
