### ISSUE TITLE
Show Analog Clock when user checked switch button

### ISSUE THREAD

**Issue by snufflesrea** [snufflesrea/MyClock#6]
On the ClockRecyclerViewAdapter, completed showAnalogClock() and showDigitalClock() method.
For showAnalogClock, digital_clock visibility should be GONE and show analog_clock
Vice versa for showDigitalClock, analog_clock visibility should be gone and show digital_clock.

**Comment by IvanSantosGonz** [comment]
I can do this

**Comment by snufflesrea** [comment]
Sure. Just push request when done and screenshoot the final look here. Thank you

**Comment by IvanSantosGonz** [comment]
Solved in PR #7
